<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AssociateMinister extends Model
{
    protected $table = 'associateministers';


    protected $fillable = [
        'file',
         'first_name', 
         'middle_name', 
         'last_name',
         'email',
         'phone',
         'mobile',
         'web',
         'education',
         'position',
         'leader_education',
         'group'
    ];
    public function getFullNameAttribute(){
        return $this->first_name.' '.$this->middle_name.' '.$this->last_name;
    }
    public function delete()
    {
        $path = 'uploads/images/associate_minister/';
        @unlink($path.$this->file);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
