<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class People extends Model
{
    protected $table = 'peoples';
    public function getFullNameAttribute(){
        return ucfirst($this->first_name.' '.$this->last_name);
    }
    public function member_categories(){
        if($this->member_category === 'church_member'){
            return 'Member';
        }elseif($this->member_category === 'visitor'){
            return 'Visitor';
        }elseif($this->member_category === 'volunteer'){
            return 'Volunteer';
        }
    }
    public function imagePath(){
        if($this->file!== null){
            return asset('uploads/images/people/'.$this->file);
        }
        return asset('church/img/avatar/avatar-02.jpg');
    }

    public function delete()
    {
        $this->child->map(function ($item,$key){
           $item->family_member_id = null;
           $item->family_status = null;
           $item->save();
        });
        $path = 'uploads/images/people/';
        @unlink($path.$this->file);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
    public function defaultAddress(){
        return $this->hasOne(PeopleAddress::class,'people_id')->where('type','default');
    }
    public function mailingAddress(){
        return $this->hasOne(PeopleAddress::class,'people_id')->where('type','mailing');
    }
    public function parent(){
        return $this->belongsTo(People::class,'family_member_id');
    }
    public function child(){
        return $this->hasMany(People::class,'family_member_id')->with(['child','parent']);
    }
    public function familyMember(){
        return $this->hasMany(People::class,'family_member_id');
    }
    public function giving(){
        return $this->hasMany(Giving::class,'contributor_id');
    }
    public function ministry(){
        return $this->belongsToMany(Ministry::class,'ministry_members','people_id','ministry_id');
    }
    public function familyMembers(){
        return $this->hasMany(FamilyMember::class,'people_id');
    }
}
